DROP DATABASE IF EXISTS itemsDB;

CREATE DATABASE itemsDB;

USE itemsDB;

CREATE TABLE products (
  id INT NOT NULL AUTO_INCREMENT,
  productName VARCHAR(50) NULL,
  minBid DECIMAL(10,2) NULL,
  currentBid DECIMAL(10,2) NULL,
  PRIMARY KEY (id)
);